### ISSUE TITLE
Width/Height switched for rotatated images.

### ISSUE THREAD

**Issue by perenstrom** [joe-bell/plaiceholder#138] opened 2021-08-07 09:52 UTC
**Describe the bug**
When inputting a remote portrait image which has been rotated by software (for example photos taken by some phones), the output width and height (`IGetImageSizeReturn`) are switched around. My problem is when fetching from Contentful, have not tested other sources.

The generated blurred placeholder also have the wrong proportions.

**To Reproduce**

1. Upload a rotated image (see picture) to contentful (or possibly other providers)
2. Run that image through Plaiceholder
3. See that width and height in the image metadata have been switched around

**Expected behavior**
Width and Height in `IGetImageSizeReturn` should respect the image orientation.

**Screenshots**
Exif data for the image:
![Screenshot 2021-08-07 at 11 41 25@2x](https://user-images.githubusercontent.com/765759/128596133-a9eae008-5872-4cf7-b724-bad290a7d4a8.png)

Props from Contentful API, with correct width and height:
![Screenshot 2021-08-07 at 11 47 21@2x](https://user-images.githubusercontent.com/765759/128596209-d14e8c85-61be-4165-83c8-0f433234fd90.png)

Props from Plaiceholder, with wrong width and height:
![Screenshot 2021-08-07 at 11 46 38@2x](https://user-images.githubusercontent.com/765759/128596216-4b883833-7d5c-45cf-bd22-7fc681101f05.png)

**Versions:**
- plaiceholder 2.0.1
- @plaiceholder/next 2.1.0

**Comment by joe-bell** [comment] 2021-08-07 20:09
Hey! Plaiceholder uses [`image-size`](https://github.com/image-size/image-size) under-the-hood but doesn't output the `orientation` value as I wanted to keep `img` to just the HTML props.

Not super comfortable with just changing around these values to match your Contentful example though as this might break other implementations

Will have to think about this, but probably won't have too much time to dig into this in the near future. In the meantime, any PRs or other suggestions are welcome!

**Comment by joe-bell** [comment] 2021-08-08 09:50
@perenstrom please could you provide a minimal reproduction to debug this further?

**Comment by perenstrom** [comment] 2021-08-10 08:01
@joe-bell Absolutely, I'll get one up as soon as possible!

**Comment by joe-bell** [comment] 2021-08-10 13:13
After a bit of digging, it seems like this is indeed [intended behaviour](https://github.com/image-size/image-size/issues/352)

Perhaps I could surface this `orientation` field in something like an `exif` key

**Comment by perenstrom** [comment] 2021-08-10 15:29
Right!

However, as an end user I would expect the behaviour to return the width and height of the picture as it is displayed on my site, not have to switch them around based on an `orientation` field. The same goes for the actual generated base 64 image, I don't even know how I _would_ rotate that.

If you chose to go with an `orientation` field, it would be amazing if you could add some documentation for manipulating the base64 image as well!

Thanks for looking into it.

**Comment by joe-bell** [comment] 2021-08-16 07:37
Are you _absolutely_ sure that the generated base64 isn't the correct orientation?

Could you please debug this by setting the [`size`](https://plaiceholder.co/docs/usage#options) to something like `64` to confirm if it's the base64 and dimensions that need rotating or just the dimensions?

I would be very surprised if the base64 image isn't the correct orientation – Plaiceholder just transforms what it's _given_

**Comment by perenstrom** [comment] 2021-08-17 13:08
I'll investigate further!

**Comment by joe-bell** [comment] 2021-09-04 20:58
@perenstrom any findings from your investigation? If not I'll close this until it's an issue again

**Comment by joe-bell** [comment] 2021-09-13 10:33
Going to close this as I've had no response in 9 days, hope you can figure something out in the meantime 😊

**Closed by joe-bell** 2021-09-13 10:33 UTC
Labels: please add a complete reproduction
