### ISSUE TITLE
Image path locked to public directory

### ISSUE THREAD

**Issue by mjasnikovs** [joe-bell/plaiceholder#211] opened 2022-08-23 08:47 UTC
Hi, I'm stuck with this problem.

src: string reference to an image. Can be either;
a file path to an image inside the root public directory, referenced from the base URL (/).
a remote image URL.

```js
const file = path.join("./public/", imagePath);
```
But why "public"? I want to use any path and directory. There should be an option to provide any path.

**Comment by joe-bell** [comment] 2022-08-23 10:15
Please use the issue templates provided

Duplicate of https://github.com/joe-bell/plaiceholder/issues/165

**Closed by joe-bell** 2022-08-23 10:15 UTC
