### ISSUE TITLE
Border radius

### ISSUE THREAD

**Issue by Karsens** [joe-bell/plaiceholder#162] opened 2021-09-16 15:29 UTC
It would be cool if your api had an option to declare border radius because this is not provided by nextjs (yet)

**Comment by joe-bell** [comment] 2021-09-16 19:00
Hey! You can do this already with custom CSS, the problem is that you need to cut against the Image component API and add it to a custom container element (see my [personal site](https://joebell.co.uk)) 

That being said, this issue is probably out of scope for this project. Best of luck

**Closed** 2021-09-16 19:00 UTC
