### ISSUE TITLE
AVIF support?

### ISSUE THREAD

**Issue by thefinnomenon** [joe-bell/plaiceholder#222] opened 2022-10-19 18:08 UTC
**Describe the bug**
What image formats does the library support? I tried to generate a placeholder for an avif image and got the following error,
```
TypeError: unsupported file type: undefined (file: undefined)
    at lookup (.../node_modules/plaiceholder/dist/index.js:84357:11)
    at imageSize (...node_modules/plaiceholder/dist/index.js:84424:14)
    at getImageSize (.../node_modules/plaiceholder/dist/index.js:84473:7)
    at loadImage (.../node_modules/plaiceholder/dist/index.js:84513:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getImage (.../node_modules/plaiceholder/dist/index.js:84583:7)
    at async getPlaiceholder (.../node_modules/plaiceholder/dist/index.js:84660:7)
```

**To Reproduce**

Call getPlaiceholder with an avif image.

**Expected behavior**
I expect the library to generate a placeholder for the image.

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 106

**Comment by joe-bell** [comment] 2022-10-19 21:31
Seems like an upstream issue with [`image-size`](https://github.com/image-size/image-size)

**Comment by wmertens** [comment] 2022-11-13 07:05
Why do you use image-size instead of sharp's metadata call?

**Comment by joe-bell** [comment] 2022-11-13 08:39
No particular reason! Feel free to raise a PR that uses `sharp` instead

**Comment by wmertens** [comment] 2022-11-13 21:02
Not sure if I'll get around to that, but it's fairly trivial:

```js
// Based on EXIF rotation metadata, get the right-side-up width and height:
const size = getNormalSize(await sharp(input).metadata());

function getNormalSize({ width, height, orientation }) {
  return (orientation || 0) >= 5
    ? { width: height, height: width }
    : { width, height };
}
```

The problem is that type field that image-size returns, is it used? Sharp has something similar but it just returns the name of the decoder, which might break something?

> format: Name of decoder used to decompress image data e.g. jpeg, png, webp, gif, svg

https://sharp.pixelplumbing.com/api-input

**Comment by joe-bell** [comment] 2023-05-17 06:17
Closing this as a future version will depend on `sharp` instead and enable support

**Closed by joe-bell** 2023-05-17 06:17 UTC
